# Generated by Django 3.2.5 on 2021-07-19 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='タイトル')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='更新時刻')),
                ('image', models.ImageField(upload_to='', verbose_name='写真')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='内容')),
            ],
        ),
    ]
