# Generated by Django 3.2.5 on 2021-07-20 16:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=100, null=True, verbose_name='主题')),
                ('published', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('image', models.ImageField(upload_to='media/', verbose_name='照片')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='内容')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
