# Generated by Django 3.2.5 on 2021-07-20 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0002_auto_20210721_0234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', null=True, upload_to='media/', verbose_name='照片'),
        ),
    ]
