# Generated by Django 3.2.5 on 2021-07-20 17:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('postapp', '0003_alter_post_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodoModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=32, null=True, verbose_name='标题')),
                ('content', models.TextField(blank=True, default='', null=True, verbose_name='具体内容')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('todo_status', models.BooleanField(default=False, verbose_name='处理状态')),
            ],
        ),
    ]
